// Copyright (c) 2016 VigLink
/*
 VigLink JavaScript Library -- http://www.viglink.com

 Permission is hereby granted to create derivative works, but only for use
 with the VigLink web service.

 Includes:

 Sizzle CSS Selector Engine v1.10.20-pre
 http://sizzlejs.com/

 Copyright 2013 jQuery Foundation, Inc. and other contributors
 Released under the MIT license
 http://jquery.org/license

 Date: 2014-05-22
*/
(function(l){var e,b={_breaker:{},_start:null,each:function(){var a;return function(c,d,f){var h,e;e=b.type(c);var k=new Date;if(1===arguments.length)a=arguments[0];else if(f=b.extend({timeout:!1},f),"object"===e&&c.hasOwnProperty)for(h in c){if(c.hasOwnProperty(h)&&(d(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a))break}else if(c){h=0;for(e=c.length;h<e&&!(d(c[h],h)===b._breaker||f.timeout&&b.elapsed(k)>a);h++);}}}(),extend:function(a){var c,d,b,h,e=arguments.length;a=a||{};for(d=1;d<e;d++)if(h=
arguments[d],void 0!==h&&null!==h)for(b in h)c=h[b],a!==c&&void 0!==c&&(a[b]=c);return a},noop:function(){},type:function(){var a=function(c,a){try{return("function"===typeof window[a]||"object"===typeof window[a])&&c instanceof window[a]}catch(b){}return!1};return function(c){return null===c?"null":void 0===c?"undefined":a(c,"HTMLElement")||"object"===typeof c&&1===c.nodeType&&"string"===typeof c.nodeName?"element":c==c.window?"window":a(c,"HTMLDocument")||"object"===typeof c&&("defaultView"in c||
"parentWindow"in c)?"document":Object.prototype.toString.call(c).slice(8,-1).toLowerCase()}}()};b.extend(b,{addClass:function(a,c){b.hasClass(a,c)||(a.className=(a.className?a.className+" ":"")+c)},all:function(a,c){var d="array"===b.type(a)?[]:{};b.each(a,function(a,h){c(a,h)&&("array"===b.type(d)?d.push(a):d[h]=a)});return d},ancestors:function(a){for(var c=[a];(a=a.parentNode)&&1===a.nodeType;)c.push(a);return c},attrValues:function(a,c,d){return(c=a[c])&&c.split?c.split(d||" "):[]},batchable:function(a,
c){c=c||b.noop;var d=function(){return b.extend({batch:!0,timeout:100},c())},f=b.traits.cors&&b.traits.json,h=[],e=null,k=function(){null!==e&&(clearTimeout(e),e=null);1===h.length?a.apply(null,h[0].arguments):1<h.length&&a.apply(null,h);h=[]},p=function(){h.push({arguments:b.toArray(arguments),batch:!0});!f||!d().batch?k():null===e&&(e=setTimeout(b.entryPoint(b.bind(function(){k()},this)),d().timeout))};b.extend(p,{flush:k,now:a});return p},batchArgs:function(a,c){return b.map(a,function(a){return void 0===
c?a.arguments:a.arguments[c]})},batched:function(a){a=b.toArray(a);if("array"===b.type(a))return b.all(a,function(c){return"object"===b.type(c)&&c.batch&&"array"===b.type(c.arguments)}).length===a.length},bind:function(a,c){return function(){return a.apply(c,arguments)}},cache:function(){var a={},c="vglnk_"+(new Date).getTime(),d=0;return function(b,h,e){if(b){var k=b[c];if(k||void 0!==e)return k||(k=++d),a[k]||(b[c]=k,a[k]={}),void 0!==e&&(a[k][h]=e),"string"===typeof h?a[k][h]:a[k]}}}(),canonicalizeHostname:function(a){"string"===
typeof a&&(a=b.createA(a));try{return a.hostname?a.hostname.toString().toLowerCase().replace(/^www\./,"").replace(/:.*$/,""):""}catch(c){return""}},clone:function(a){return b.extend({},a)},contains:function(a,c){return Boolean(b.find(a,function(a){return a===c}))},context:function(a){"element"===b.type(a)&&(a=a.ownerDocument);"document"===b.type(a)&&(a=a.defaultView||a.parentWindow);if("window"===b.type(a))return a},contextIsAncestor:function(a,c){for(var d=a.self;d.parent&&d.parent!==d;)if(d=d.parent,
d===c)return!0;return!1},cors:function(a,c,d){var b,h=function(){d?d(b.responseText):eval(b.responseText)};b=new window.XMLHttpRequest;b.onreadystatechange=function(){4===b.readyState&&200===b.status&&h()};try{return b.open("POST",a),b.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),b.withCredentials=!0,b.send(c),!0}catch(e){return!1}},createA:function(a,c){return b.createEl("a",{href:a,target:c})},createEl:function(a,c,d,f){var h;a=(f||document).createElement(a);c=c||{};d=d||
{};for(h in c)void 0!==c[h]&&(a[h]=c[h]);b.css(a,d);return a},css:function(a,c){for(var b in c)try{a.style[b]=c[b]}catch(f){}return a},destructing:function(a){return function(a){var b=!1,f;return function(){b||(f=a.apply(null,arguments),b=!0);return f}}(a)},elapsed:function(a){return(a=a||this._start)?(new Date).getTime()-a.getTime():0},entryPoint:function(a){return b.exceptionLogger(function(){var c;b._start=new Date;b.observer.pause();c=a.apply(this,arguments);b.observer.resume();return c})},escapeRegExp:function(){var a;
return function(c){a=a||/([.*+?^${}()|[\]\\])/g;return c.replace(a,"\\$1")}}(),eventLink:function(a){var c,b=a.target||a.srcElement;do{try{c=b.nodeType}catch(f){break}if(1===c&&(a=b.tagName.toUpperCase(),"A"===a||"AREA"===a))return b;b=b.parentNode}while(b)},every:function(a,c){return Boolean(!b.some(a,function(a){return!c(a)}))},exceptionLogger:function(){var a=!1,c=b.noop;return function(b,f){if(void 0!==f)a=f,c=b;else return function(){if(a)try{return b.apply(this,arguments)}catch(f){c(f)}else return b.apply(this,
arguments)}}}(),find:function(a,c,d){var f;b.each(a,function(a,d){if(c(a,d))return f=a,b._breaker},d);return f},generateNodeFilter:function(){var a=function(a,b){var h,e;b=","+b.join(",")+",";h=0;for(e=a.length;h<e;h++)if(c(a[h],b))return!0;return!1},c=function(a,c){return-1!==c.indexOf(","+a+",")};return function(d){d=b.extend({custom:null,classes:[],rels:[],tags:[]},d);d.tags.length&&(d.tags=","+d.tags.join(",").toLowerCase()+",");return function(f,h){h=b.extend({ancestors:!0,self:!0},h);var e=
function(f,h){var e;if(e=!(d.tags.length&&c(f.nodeName.toLowerCase(),d.tags))){if(e=d.classes.length){e=d.classes;var w=b.attrValues(f,"className");e=a(e,w)}if(e=!e){if(e=d.rels.length)e=d.rels,w=b.attrValues(f,"rel"),e=c(f.nodeName.toLowerCase(),",a,")&&a(e,w);e=!e&&!("function"===b.type(d.custom)&&d.custom(f,h))}}return e};if(h.self&&!e(f,!0))return!1;if(h.ancestors)for(;f.parentNode;)if(f=f.parentNode,1===f.nodeType&&!e(f,!1))return!1;return!0}}}(),fromJSON:function(a){if(b.traits.json)try{return window.JSON.parse(a)}catch(c){}},
fromQuery:function(a){"?"===a.substr(0,1)&&(a=a.substr(1));a=a.split("&");var c={};b.each(a,function(a){a=a.split("=");c[decodeURIComponent(a[0])]=decodeURIComponent(a[1])});return c},geometry:function(){var a,c=arguments.length,d=Infinity,f=Infinity,h=-Infinity,e=-Infinity,k;for(a=0;a<c;a++)k=b.position(arguments[a]),d=Math.min(d,k.x),f=Math.min(f,k.y),h=Math.max(h,k.x+arguments[a].offsetWidth),e=Math.max(e,k.y+arguments[a].offsetHeight);return{x:d,y:f,w:h-d,h:e-f,x1:d,y1:f,x2:h,y2:e}},getActualHref:function(a){return b.cache(a,
"href")||a.href},hasAttrValue:function(a,c,d,f){return c?b.contains(b.attrValues(a,c,f),d):!1},hasClass:function(a,c){return b.hasAttrValue(a,"className",c)},hasRel:function(a,c){return b.hasAttrValue(a,"rel",c)},isArray:function(a){return"array"===b.type(a)},isDefaultPrevented:function(a){return a.isDefaultPrevented&&a.isDefaultPrevented()||!1===a.returnValue||!0===a.defaultPrevented},isInDom:function(a){return Boolean(a&&a.offsetParent)},jsonp:function(a){var c=document.getElementsByTagName("script")[0];
a=b.createEl("script",{type:"text/javascript",src:a});c.parentNode.insertBefore(a,c)},map:function(a,c,d){return b.reduce([],a,function(a,b,d){a.push(c(b,d));return a},d)},matches:function(a,c){if("element"!==b.type(a))return!1;try{return this.Sizzle.matchesSelector(a,c)}catch(d){return!0}},nodesOfType:function(a){var c=b.toArray(arguments).slice(1);return b.all(a,function(a){return b.contains(c,a.nodeType)})},on:function(){var a;return function(c,d,f){var h,e,k;if(1===arguments.length)a=c;else{if(2===
arguments.length){if(!a)return;f=d;d=c;c=a}else h=b.toArray(arguments).slice(3,arguments.length);try{e=c["on"+d]}catch(p){}"function"===typeof e&&(c["on"+d]=b.bind(function(a){a=a||window.event;var d=e.apply(c,arguments);this.exceptionLogger(function(){return a?(void 0!==d&&!1!==a.returnValue&&(a.returnValue=d),b.isDefaultPrevented(a)&&"function"===b.type(a.preventDefault)&&a.preventDefault(),a.returnValue):d})()},this));k=b.entryPoint(function(){if(a.enabled())return f.apply(null,b.toArray(arguments).concat(h||
[]))});c.addEventListener?c.addEventListener(d,k,!1):c.attachEvent&&c.attachEvent("on"+d,k)}}}(),position:function(a,c){var d,f=0,h=0,e=0,k=0;c=c||document;if(!b.isInDom(a))return!1;d=a;do f+=d.offsetLeft,h+=d.offsetTop,d=d.offsetParent;while(d);d=a;do e+=d.scrollLeft,k+=d.scrollTop,d=d.parentNode;while(d&&d!==c.body);return{x:f-e,y:h-k}},preventDefault:function(a){a.preventDefault&&a.preventDefault();return a.returnValue=!1},prune:function(a){b.each(a,function(c,b){(null===c||void 0===c)&&delete a[b]});
return a},ready:function(){var a=!1,c=[],d=!1,f,h,e,k,p;document.addEventListener?e=function(){document.removeEventListener("DOMContentLoaded",e,!1);p()}:document.attachEvent&&(k=function(){"complete"===document.readyState&&(document.detachEvent("onreadystatechange",k),p())});f=function(){if(!a){a=!0;if("interactive"===document.readyState||"complete"===document.readyState)return p();if(document.addEventListener)document.addEventListener("DOMContentLoaded",e,!1);else if(document.attachEvent){document.attachEvent("onreadystatechange",
k);var c=!1;try{c=null===window.frameElement}catch(d){}document.documentElement.doScroll&&c&&h()}b.on(window,"load",p)}};h=function(){if(!d){try{document.documentElement.doScroll("left")}catch(a){setTimeout(b.entryPoint(h),1);return}p()}};p=function(){if(!d){if(!document.body)return setTimeout(b.entryPoint(p),13);d=!0;c&&(b.each(c,function(a){a()}),c=null)}};return function(a){f();d?a():c.push(a)}}(),reduce:function(a,c,d,f){b.each(c,function(c,b){a=d(a,c,b)},f);return a},reformatKeys:function(a){var c,
d,f=function(a){return"_"+a.toLowerCase()};for(c in a)d=c.replace(/([A-Z])/g,f),"object"===b.type(a[c])&&(a[c]=b.reformatKeys(a[c])),d!==c&&(a[d]=a[c],delete a[c]);return a},removeClass:function(a,c){if(b.hasClass(a,c)){var d,f,h=b.attrValues(a,"className");d=0;for(f=h.length;d<f;d++)h[d]===c&&delete h[d];a.className=h.join(" ")}},request:function(a,c,d){var f,h,e,k=b.uniqid("vglnk_"),p=b.toArray(arguments).slice(3,arguments.length),s=function(a,c,d){var f=b.createA(a).protocol;c.length&&(a=b.updateUrl(a,
{search:"?"+c}));if(!0===d||!1===d)a=b.updateUrl(a,{protocol:f.replace(/s?:$/,function(){return d?"s:":":"})});return a};d=b.extend({fn:b.noop,jsonp:!0,"return":!1,ssl:null,timeout:null},d);"string"===typeof d.fn?(f=window[d.fn],k=d.fn):"function"===typeof d.fn&&(f=d.fn);"function"===b.type(f)&&(e=b.entryPoint(b.destructing(function(){f.apply(this,b.toArray(arguments).concat(p));window[k]&&(window[k]=void 0)})),null!==d.timeout&&setTimeout(e,d.timeout));!0===d.jsonp&&(window[k]=e,c=b.extend({format:"jsonp",
jsonp:k},c));h=b.toQuery(c);return d["return"]?s(a,h,d.ssl):b.traits.cors&&b.cors(s(a,"",d.ssl),h,d.jsonp?null:e)?!0:b.jsonp(s(a,h,d.ssl))},select:function(){try{return this.Sizzle.apply(this.Sizzle,arguments)}catch(a){return[]}},some:function(a,c){return Boolean(b.find(a,function(a){return c(a)}))},stopPropagation:function(a){a&&a.stopPropagation&&a.stopPropagation();a.cancelBubble=!0},time:function(){return(new Date).getTime()},toArray:function(a){if(a&&void 0!==a.length)try{return Array.prototype.slice.call(a,
0)}catch(c){var b,f,h=[];b=0;for(f=a.length;b<f;b++)h[b]=a[b];return h}},toJSON:function(a){if(b.traits.json)try{return window.JSON.stringify(a)}catch(c){}},toQuery:function(a){var c="";b.each(b.prune(a),function(a,b){c+="&"+encodeURIComponent(b)+"="+encodeURIComponent(a)});return c.substr(1)},updateUrl:function(a,c){return b.extend(b.createA(a),c).href},uniqid:function(){var a=0;return function(c){return(c||"")+(new Date).getTime()+a++}}(),unique:function(a){return b.reduce([],a,function(a,d){b.contains(a,
d)||a.push(d);return a})},unlink:function(a){var c,b=document.createDocumentFragment();if(a.parentNode){for(;null!==(c=a.firstChild);)b.appendChild(c);a.parentNode.insertBefore(b,a);a.parentNode.removeChild(a)}},withScope:function(){var a=function(a,d,f){if(f.self&&b.contains(d,a))return a;if(f.ancestors)return b.find(b.ancestors(a).slice(0),function(a){return b.contains(d,a)},{timeout:!0})};return function(c,d,f){var h=b.select(d);f=b.extend({ancestors:!0,consolidate:!1,descendants:!0,self:!0},f);
c=b.all(b.map(c,function(c){var d,e=[];(d=a(c,h,f))?e.push(d):1===c.nodeType&&f.descendants&&b.each(h,function(a){b.contains(b.ancestors(a),c)&&e.push(a)},{timeout:!0});return[c,e]},{timeout:!0}),function(a){return 0<a[1].length},{timeout:!0});return f.consolidate?b.reduce([],c,function(a,c){return a.concat(c[1])}):c}}()});var r=function(){var a=b.find(b.toArray(arguments),function(a){return"function"===b.type(a)});a&&(b.Sizzle=a())};r.amd=!0;(function(a){function c(a,c,b,d){var f,e,h,k,g;(c?c.ownerDocument||
c:B)!==z&&H(c);c=c||z;b=b||[];if(!a||"string"!==typeof a)return b;if(1!==(k=c.nodeType)&&9!==k)return[];if(D&&!d){if(f=sa.exec(a))if(h=f[1])if(9===k)if((e=c.getElementById(h))&&e.parentNode){if(e.id===h)return b.push(e),b}else return b;else{if(c.ownerDocument&&(e=c.ownerDocument.getElementById(h))&&R(c,e)&&e.id===h)return b.push(e),b}else{if(f[2])return I.apply(b,c.getElementsByTagName(a)),b;if((h=f[3])&&v.getElementsByClassName&&c.getElementsByClassName)return I.apply(b,c.getElementsByClassName(h)),
b}if(v.qsa&&(!A||!A.test(a))){e=f=x;h=c;g=9===k&&a;if(1===k&&"object"!==c.nodeName.toLowerCase()){k=S(a);(f=c.getAttribute("id"))?e=f.replace(ta,"\\$&"):c.setAttribute("id",e);e="[id='"+e+"'] ";for(h=k.length;h--;)k[h]=e+q(k[h]);h=ea.test(a)&&m(c.parentNode)||c;g=k.join(",")}if(g)try{return I.apply(b,h.querySelectorAll(g)),b}catch(s){}finally{f||c.removeAttribute("id")}}}return ka(a.replace(X,"$1"),c,b,d)}function b(){function a(b,d){c.push(b+" ")>t.cacheLength&&delete a[c.shift()];return a[b+" "]=
d}var c=[];return a}function f(a){a[x]=!0;return a}function h(a){var c=z.createElement("div");try{return!!a(c)}catch(b){return!1}finally{c.parentNode&&c.parentNode.removeChild(c)}}function e(a,c){for(var b=a.split("|"),d=a.length;d--;)t.attrHandle[b[d]]=c}function k(a,c){var b=c&&a,d=b&&1===a.nodeType&&1===c.nodeType&&(~c.sourceIndex||la)-(~a.sourceIndex||la);if(d)return d;if(b)for(;b=b.nextSibling;)if(b===c)return-1;return a?1:-1}function g(a){return function(c){return"input"===c.nodeName.toLowerCase()&&
c.type===a}}function s(a){return function(c){var b=c.nodeName.toLowerCase();return("input"===b||"button"===b)&&c.type===a}}function n(a){return f(function(c){c=+c;return f(function(b,d){for(var f,e=a([],b.length,c),h=e.length;h--;)if(b[f=e[h]])b[f]=!(d[f]=b[f])})})}function m(a){return a&&typeof a.getElementsByTagName!==N&&a}function l(){}function q(a){for(var c=0,b=a.length,d="";c<b;c++)d+=a[c].value;return d}function u(a,c,b){var d=c.dir,f=b&&"parentNode"===d,e=ua++;return c.first?function(c,b,
e){for(;c=c[d];)if(1===c.nodeType||f)return a(c,b,e)}:function(c,b,h){var W,k,ca=[C,e];if(h)for(;c=c[d];){if((1===c.nodeType||f)&&a(c,b,h))return!0}else for(;c=c[d];)if(1===c.nodeType||f){k=c[x]||(c[x]={});if((W=k[d])&&W[0]===C&&W[1]===e)return ca[2]=W[2];k[d]=ca;if(ca[2]=a(c,b,h))return!0}}}function fa(a){return 1<a.length?function(c,b,d){for(var f=a.length;f--;)if(!a[f](c,b,d))return!1;return!0}:a[0]}function Y(a,c,b,d,f){for(var e,h=[],k=0,g=a.length,s=null!=c;k<g;k++)if(e=a[k])if(!b||b(e,d,f))h.push(e),
s&&c.push(k);return h}function ga(a,b,d,e,h,k){e&&!e[x]&&(e=ga(e));h&&!h[x]&&(h=ga(h,k));return f(function(f,k,g,s){var p,n,w=[],y=[],m=k.length,l;if(!(l=f)){l=b||"*";for(var q=g.nodeType?[g]:g,Q=[],da=0,u=q.length;da<u;da++)c(l,q[da],Q);l=Q}l=a&&(f||!b)?Y(l,w,a,g,s):l;q=d?h||(f?a:m||e)?[]:k:l;d&&d(l,q,g,s);if(e){p=Y(q,y);e(p,[],g,s);for(g=p.length;g--;)if(n=p[g])q[y[g]]=!(l[y[g]]=n)}if(f){if(h||a){if(h){p=[];for(g=q.length;g--;)if(n=q[g])p.push(l[g]=n);h(null,q=[],p,s)}for(g=q.length;g--;)if((n=
q[g])&&-1<(p=h?L.call(f,n):w[g]))f[p]=!(k[p]=n)}}else q=Y(q===k?q.splice(m,q.length):q),h?h(null,k,q,s):I.apply(k,q)})}function T(a){var c,b,d,f=a.length,e=t.relative[a[0].type];b=e||t.relative[" "];for(var h=e?1:0,k=u(function(a){return a===c},b,!0),g=u(function(a){return-1<L.call(c,a)},b,!0),s=[function(a,b,d){return!e&&(d||b!==Z)||((c=b).nodeType?k(a,b,d):g(a,b,d))}];h<f;h++)if(b=t.relative[a[h].type])s=[u(fa(s),b)];else{b=t.filter[a[h].type].apply(null,a[h].matches);if(b[x]){for(d=++h;d<f&&!t.relative[a[d].type];d++);
return ga(1<h&&fa(s),1<h&&q(a.slice(0,h-1).concat({value:" "===a[h-2].type?"*":""})).replace(X,"$1"),b,h<d&&T(a.slice(h,d)),d<f&&T(a=a.slice(d)),d<f&&q(a))}s.push(b)}return fa(s)}function va(a,b){var d=0<b.length,h=0<a.length,e=function(f,e,k,g,s){var p,n,w,y=0,m="0",q=f&&[],l=[],Q=Z,ja=f||h&&t.find.TAG("*",s),u=C+=null==Q?1:Math.random()||0.1,ra=ja.length;for(s&&(Z=e!==z&&e);m!==ra&&null!=(p=ja[m]);m++){if(h&&p){for(n=0;w=a[n++];)if(w(p,e,k)){g.push(p);break}s&&(C=u)}d&&((p=!w&&p)&&y--,f&&q.push(p))}y+=
m;if(d&&m!==y){for(n=0;w=b[n++];)w(q,l,e,k);if(f){if(0<y)for(;m--;)!q[m]&&!l[m]&&(l[m]=wa.call(g));l=Y(l)}I.apply(g,l);s&&(!f&&0<l.length&&1<y+b.length)&&c.uniqueSort(g)}s&&(C=u,Z=Q);return q};return d?f(e):e}var O,v,t,$,ma,S,ha,ka,Z,J,P,H,z,E,D,A,M,aa,R,x="sizzle"+-new Date,B=a.document,C=0,ua=0,na=b(),oa=b(),pa=b(),ia=function(a,c){a===c&&(P=!0);return 0},N="undefined",la=-2147483648,xa={}.hasOwnProperty,K=[],wa=K.pop,ya=K.push,I=K.push,qa=K.slice,L=K.indexOf||function(a){for(var c=0,b=this.length;c<
b;c++)if(this[c]===a)return c;return-1},X=/^[\x20\t\r\n\f]+|((?:^|[^\\])(?:\\.)*)[\x20\t\r\n\f]+$/g,za=/^[\x20\t\r\n\f]*,[\x20\t\r\n\f]*/,Aa=/^[\x20\t\r\n\f]*([>+~]|[\x20\t\r\n\f])[\x20\t\r\n\f]*/,Ba=/=[\x20\t\r\n\f]*([^\]'"]*?)[\x20\t\r\n\f]*\]/g,Ca=RegExp(":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
Da=/^(?:\\.|[\w-]|[^\x00-\xa0])+$/,ba={ID:/^#((?:\\.|[\w-]|[^\x00-\xa0])+)/,CLASS:/^\.((?:\\.|[\w-]|[^\x00-\xa0])+)/,TAG:/^((?:\\.|[\w-]|[^\x00-\xa0])+|[*])/,ATTR:RegExp("^\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\]"),PSEUDO:RegExp("^:((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)"),
CHILD:RegExp("^:(only|first|last|nth|nth-last)-(child|of-type)(?:\\([\\x20\\t\\r\\n\\f]*(even|odd|(([+-]|)(\\d*)n|)[\\x20\\t\\r\\n\\f]*(?:([+-]|)[\\x20\\t\\r\\n\\f]*(\\d+)|))[\\x20\\t\\r\\n\\f]*\\)|)","i"),bool:RegExp("^(?:checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)$","i"),needsContext:RegExp("^[\\x20\\t\\r\\n\\f]*[>+~]|:(even|odd|eq|gt|lt|nth|first|last)(?:\\([\\x20\\t\\r\\n\\f]*((?:-\\d)?\\d*)[\\x20\\t\\r\\n\\f]*\\)|)(?=[^-]|$)",
"i")},Ea=/^(?:input|select|textarea|button)$/i,Fa=/^h\d$/i,U=/^[^{]+\{\s*\[native \w/,sa=/^(?:#([\w-]+)|(\w+)|\.([\w-]+))$/,ea=/[+~]/,ta=/'|\\/g,F=/\\([\da-f]{1,6}[\x20\t\r\n\f]?|([\x20\t\r\n\f])|.)/ig,G=function(a,c,b){a="0x"+c-65536;return a!==a||b?c:0>a?String.fromCharCode(a+65536):String.fromCharCode(a>>10|55296,a&1023|56320)};try{I.apply(K=qa.call(B.childNodes),B.childNodes),K[B.childNodes.length].nodeType}catch(Ga){I={apply:K.length?function(a,c){ya.apply(a,qa.call(c))}:function(a,c){for(var b=
a.length,d=0;a[b++]=c[d++];);a.length=b-1}}}v=c.support={};ma=c.isXML=function(a){return(a=a&&(a.ownerDocument||a).documentElement)?"HTML"!==a.nodeName:!1};H=c.setDocument=function(a){var c=a?a.ownerDocument||a:B;a=c.defaultView;if(c===z||9!==c.nodeType||!c.documentElement)return z;z=c;E=c.documentElement;D=!ma(c);a&&a!==a.top&&(a.addEventListener?a.addEventListener("unload",function(){H()},!1):a.attachEvent&&a.attachEvent("onunload",function(){H()}));v.attributes=h(function(a){a.className="i";return!a.getAttribute("className")});
v.getElementsByTagName=h(function(a){a.appendChild(c.createComment(""));return!a.getElementsByTagName("*").length});v.getElementsByClassName=U.test(c.getElementsByClassName)&&h(function(a){a.innerHTML="<div class='a'></div><div class='a i'></div>";a.firstChild.className="i";return 2===a.getElementsByClassName("i").length});v.getById=h(function(a){E.appendChild(a).id=x;return!c.getElementsByName||!c.getElementsByName(x).length});v.getById?(t.find.ID=function(a,c){if(typeof c.getElementById!==N&&D){var b=
c.getElementById(a);return b&&b.parentNode?[b]:[]}},t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return a.getAttribute("id")===c}}):(delete t.find.ID,t.filter.ID=function(a){var c=a.replace(F,G);return function(a){return(a=typeof a.getAttributeNode!==N&&a.getAttributeNode("id"))&&a.value===c}});t.find.TAG=v.getElementsByTagName?function(a,c){if(typeof c.getElementsByTagName!==N)return c.getElementsByTagName(a)}:function(a,c){var b,d=[],f=0,h=c.getElementsByTagName(a);if("*"===a){for(;b=
h[f++];)1===b.nodeType&&d.push(b);return d}return h};t.find.CLASS=v.getElementsByClassName&&function(a,c){if(typeof c.getElementsByClassName!==N&&D)return c.getElementsByClassName(a)};M=[];A=[];if(v.qsa=U.test(c.querySelectorAll))h(function(a){a.innerHTML="<select msallowclip=''><option selected=''></option></select>";a.querySelectorAll("[msallowclip^='']").length&&A.push("[*^$]=[\\x20\\t\\r\\n\\f]*(?:''|\"\")");a.querySelectorAll("[selected]").length||A.push("\\[[\\x20\\t\\r\\n\\f]*(?:value|checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped)");
a.querySelectorAll(":checked").length||A.push(":checked")}),h(function(a){var b=c.createElement("input");b.setAttribute("type","hidden");a.appendChild(b).setAttribute("name","D");a.querySelectorAll("[name=d]").length&&A.push("name[\\x20\\t\\r\\n\\f]*[*^$|!~]?=");a.querySelectorAll(":enabled").length||A.push(":enabled",":disabled");a.querySelectorAll("*,:x");A.push(",.*:")});(v.matchesSelector=U.test(aa=E.matches||E.webkitMatchesSelector||E.mozMatchesSelector||E.oMatchesSelector||E.msMatchesSelector))&&
h(function(a){v.disconnectedMatch=aa.call(a,"div");aa.call(a,"[s!='']:x");M.push("!=",":((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:\\((('((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\")|((?:\\\\.|[^\\\\()[\\]]|\\[[\\x20\\t\\r\\n\\f]*((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+)(?:[\\x20\\t\\r\\n\\f]*([*^$|!~]?=)[\\x20\\t\\r\\n\\f]*(?:'((?:\\\\.|[^\\\\'])*)'|\"((?:\\\\.|[^\\\\\"])*)\"|((?:\\\\.|[\\w-]|[^\\x00-\\xa0])+))|)[\\x20\\t\\r\\n\\f]*\\])*)|.*)\\)|)")});A=A.length&&RegExp(A.join("|"));M=M.length&&RegExp(M.join("|"));
R=(a=U.test(E.compareDocumentPosition))||U.test(E.contains)?function(a,c){var b=9===a.nodeType?a.documentElement:a,d=c&&c.parentNode;return a===d||!(!d||!(1===d.nodeType&&(b.contains?b.contains(d):a.compareDocumentPosition&&a.compareDocumentPosition(d)&16)))}:function(a,c){if(c)for(;c=c.parentNode;)if(c===a)return!0;return!1};ia=a?function(a,b){if(a===b)return P=!0,0;var d=!a.compareDocumentPosition-!b.compareDocumentPosition;if(d)return d;d=(a.ownerDocument||a)===(b.ownerDocument||b)?a.compareDocumentPosition(b):
1;return d&1||!v.sortDetached&&b.compareDocumentPosition(a)===d?a===c||a.ownerDocument===B&&R(B,a)?-1:b===c||b.ownerDocument===B&&R(B,b)?1:J?L.call(J,a)-L.call(J,b):0:d&4?-1:1}:function(a,b){if(a===b)return P=!0,0;var d,f=0;d=a.parentNode;var h=b.parentNode,e=[a],V=[b];if(!d||!h)return a===c?-1:b===c?1:d?-1:h?1:J?L.call(J,a)-L.call(J,b):0;if(d===h)return k(a,b);for(d=a;d=d.parentNode;)e.unshift(d);for(d=b;d=d.parentNode;)V.unshift(d);for(;e[f]===V[f];)f++;return f?k(e[f],V[f]):e[f]===B?-1:V[f]===
B?1:0};return c};c.matches=function(a,b){return c(a,null,null,b)};c.matchesSelector=function(a,b){(a.ownerDocument||a)!==z&&H(a);b=b.replace(Ba,"='$1']");if(v.matchesSelector&&D&&(!M||!M.test(b))&&(!A||!A.test(b)))try{var d=aa.call(a,b);if(d||v.disconnectedMatch||a.document&&11!==a.document.nodeType)return d}catch(f){}return 0<c(b,z,null,[a]).length};c.contains=function(a,c){(a.ownerDocument||a)!==z&&H(a);return R(a,c)};c.attr=function(a,c){(a.ownerDocument||a)!==z&&H(a);var b=t.attrHandle[c.toLowerCase()],
b=b&&xa.call(t.attrHandle,c.toLowerCase())?b(a,c,!D):void 0;return void 0!==b?b:v.attributes||!D?a.getAttribute(c):(b=a.getAttributeNode(c))&&b.specified?b.value:null};c.error=function(a){throw Error("Syntax error, unrecognized expression: "+a);};c.uniqueSort=function(a){var c,b=[],d=0,f=0;P=!v.detectDuplicates;J=!v.sortStable&&a.slice(0);a.sort(ia);if(P){for(;c=a[f++];)c===a[f]&&(d=b.push(f));for(;d--;)a.splice(b[d],1)}J=null;return a};$=c.getText=function(a){var c,b="",d=0;if(c=a.nodeType)if(1===
c||9===c||11===c){if("string"===typeof a.textContent)return a.textContent;for(a=a.firstChild;a;a=a.nextSibling)b+=$(a)}else{if(3===c||4===c)return a.nodeValue}else for(;c=a[d++];)b+=$(c);return b};t=c.selectors={cacheLength:50,createPseudo:f,match:ba,attrHandle:{},find:{},relative:{">":{dir:"parentNode",first:!0}," ":{dir:"parentNode"},"+":{dir:"previousSibling",first:!0},"~":{dir:"previousSibling"}},preFilter:{ATTR:function(a){a[1]=a[1].replace(F,G);a[3]=(a[3]||a[4]||a[5]||"").replace(F,G);"~="===
a[2]&&(a[3]=" "+a[3]+" ");return a.slice(0,4)},CHILD:function(a){a[1]=a[1].toLowerCase();"nth"===a[1].slice(0,3)?(a[3]||c.error(a[0]),a[4]=+(a[4]?a[5]+(a[6]||1):2*("even"===a[3]||"odd"===a[3])),a[5]=+(a[7]+a[8]||"odd"===a[3])):a[3]&&c.error(a[0]);return a},PSEUDO:function(a){var c,b=!a[6]&&a[2];if(ba.CHILD.test(a[0]))return null;if(a[3])a[2]=a[4]||a[5]||"";else if(b&&Ca.test(b)&&(c=S(b,!0))&&(c=b.indexOf(")",b.length-c)-b.length))a[0]=a[0].slice(0,c),a[2]=b.slice(0,c);return a.slice(0,3)}},filter:{TAG:function(a){var c=
a.replace(F,G).toLowerCase();return"*"===a?function(){return!0}:function(a){return a.nodeName&&a.nodeName.toLowerCase()===c}},CLASS:function(a){var c=na[a+" "];return c||(c=RegExp("(^|[\\x20\\t\\r\\n\\f])"+a+"([\\x20\\t\\r\\n\\f]|$)"))&&na(a,function(a){return c.test("string"===typeof a.className&&a.className||typeof a.getAttribute!==N&&a.getAttribute("class")||"")})},ATTR:function(a,b,d){return function(f){f=c.attr(f,a);if(null==f)return"!="===b;if(!b)return!0;f+="";return"="===b?f===d:"!="===b?
f!==d:"^="===b?d&&0===f.indexOf(d):"*="===b?d&&-1<f.indexOf(d):"$="===b?d&&f.slice(-d.length)===d:"~="===b?-1<(" "+f+" ").indexOf(d):"|="===b?f===d||f.slice(0,d.length+1)===d+"-":!1}},CHILD:function(a,c,b,d,f){var h="nth"!==a.slice(0,3),e="last"!==a.slice(-4),k="of-type"===c;return 1===d&&0===f?function(a){return!!a.parentNode}:function(c,b,g){var s,p,n,w,m;b=h!==e?"nextSibling":"previousSibling";var y=c.parentNode,q=k&&c.nodeName.toLowerCase();g=!g&&!k;if(y){if(h){for(;b;){for(p=c;p=p[b];)if(k?p.nodeName.toLowerCase()===
q:1===p.nodeType)return!1;m=b="only"===a&&!m&&"nextSibling"}return!0}m=[e?y.firstChild:y.lastChild];if(e&&g){g=y[x]||(y[x]={});s=g[a]||[];w=s[0]===C&&s[1];n=s[0]===C&&s[2];for(p=w&&y.childNodes[w];p=++w&&p&&p[b]||(n=w=0)||m.pop();)if(1===p.nodeType&&++n&&p===c){g[a]=[C,w,n];break}}else if(g&&(s=(c[x]||(c[x]={}))[a])&&s[0]===C)n=s[1];else for(;p=++w&&p&&p[b]||(n=w=0)||m.pop();)if((k?p.nodeName.toLowerCase()===q:1===p.nodeType)&&++n)if(g&&((p[x]||(p[x]={}))[a]=[C,n]),p===c)break;n-=f;return n===d||
0===n%d&&0<=n/d}}},PSEUDO:function(a,b){var d,h=t.pseudos[a]||t.setFilters[a.toLowerCase()]||c.error("unsupported pseudo: "+a);return h[x]?h(b):1<h.length?(d=[a,a,"",b],t.setFilters.hasOwnProperty(a.toLowerCase())?f(function(a,c){for(var d,f=h(a,b),e=f.length;e--;)d=L.call(a,f[e]),a[d]=!(c[d]=f[e])}):function(a){return h(a,0,d)}):h}},pseudos:{not:f(function(a){var c=[],b=[],d=ha(a.replace(X,"$1"));return d[x]?f(function(a,c,b,f){f=d(a,null,f,[]);for(var h=a.length;h--;)if(b=f[h])a[h]=!(c[h]=b)}):
function(a,f,h){c[0]=a;d(c,null,h,b);return!b.pop()}}),has:f(function(a){return function(b){return 0<c(a,b).length}}),contains:f(function(a){a=a.replace(F,G);return function(c){return-1<(c.textContent||c.innerText||$(c)).indexOf(a)}}),lang:f(function(a){Da.test(a||"")||c.error("unsupported lang: "+a);a=a.replace(F,G).toLowerCase();return function(c){var b;do if(b=D?c.lang:c.getAttribute("xml:lang")||c.getAttribute("lang"))return b=b.toLowerCase(),b===a||0===b.indexOf(a+"-");while((c=c.parentNode)&&
1===c.nodeType);return!1}}),target:function(c){var b=a.location&&a.location.hash;return b&&b.slice(1)===c.id},root:function(a){return a===E},focus:function(a){return a===z.activeElement&&(!z.hasFocus||z.hasFocus())&&!(!a.type&&!a.href&&!~a.tabIndex)},enabled:function(a){return!1===a.disabled},disabled:function(a){return!0===a.disabled},checked:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&!!a.checked||"option"===c&&!!a.selected},selected:function(a){a.parentNode&&a.parentNode.selectedIndex;
return!0===a.selected},empty:function(a){for(a=a.firstChild;a;a=a.nextSibling)if(6>a.nodeType)return!1;return!0},parent:function(a){return!t.pseudos.empty(a)},header:function(a){return Fa.test(a.nodeName)},input:function(a){return Ea.test(a.nodeName)},button:function(a){var c=a.nodeName.toLowerCase();return"input"===c&&"button"===a.type||"button"===c},text:function(a){var c;return"input"===a.nodeName.toLowerCase()&&"text"===a.type&&(null==(c=a.getAttribute("type"))||"text"===c.toLowerCase())},first:n(function(){return[0]}),
last:n(function(a,c){return[c-1]}),eq:n(function(a,c,b){return[0>b?b+c:b]}),even:n(function(a,c){for(var b=0;b<c;b+=2)a.push(b);return a}),odd:n(function(a,c){for(var b=1;b<c;b+=2)a.push(b);return a}),lt:n(function(a,c,b){for(c=0>b?b+c:b;0<=--c;)a.push(c);return a}),gt:n(function(a,c,b){for(b=0>b?b+c:b;++b<c;)a.push(b);return a})}};t.pseudos.nth=t.pseudos.eq;for(O in{radio:!0,checkbox:!0,file:!0,password:!0,image:!0})t.pseudos[O]=g(O);for(O in{submit:!0,reset:!0})t.pseudos[O]=s(O);l.prototype=t.filters=
t.pseudos;t.setFilters=new l;S=c.tokenize=function(a,b){var d,f,h,e,k,g,p;if(k=oa[a+" "])return b?0:k.slice(0);k=a;g=[];for(p=t.preFilter;k;){if(!d||(f=za.exec(k)))f&&(k=k.slice(f[0].length)||k),g.push(h=[]);d=!1;if(f=Aa.exec(k))d=f.shift(),h.push({value:d,type:f[0].replace(X," ")}),k=k.slice(d.length);for(e in t.filter)if((f=ba[e].exec(k))&&(!p[e]||(f=p[e](f))))d=f.shift(),h.push({value:d,type:e,matches:f}),k=k.slice(d.length);if(!d)break}return b?k.length:k?c.error(a):oa(a,g).slice(0)};ha=c.compile=
function(a,c){var b,d=[],f=[],h=pa[a+" "];if(!h){c||(c=S(a));for(b=c.length;b--;)h=T(c[b]),h[x]?d.push(h):f.push(h);h=pa(a,va(f,d));h.selector=a}return h};ka=c.select=function(a,c,b,d){var f,h,e,k,g="function"===typeof a&&a,p=!d&&S(a=g.selector||a);b=b||[];if(1===p.length){h=p[0]=p[0].slice(0);if(2<h.length&&"ID"===(e=h[0]).type&&v.getById&&9===c.nodeType&&D&&t.relative[h[1].type]){if(c=(t.find.ID(e.matches[0].replace(F,G),c)||[])[0])g&&(c=c.parentNode);else return b;a=a.slice(h.shift().value.length)}for(f=
ba.needsContext.test(a)?0:h.length;f--;){e=h[f];if(t.relative[k=e.type])break;if(k=t.find[k])if(d=k(e.matches[0].replace(F,G),ea.test(h[0].type)&&m(c.parentNode)||c)){h.splice(f,1);a=d.length&&q(h);if(!a)return I.apply(b,d),b;break}}}(g||ha(a,p))(d,c,!D,b,ea.test(a)&&m(c.parentNode)||c);return b};v.sortStable=x.split("").sort(ia).join("")===x;v.detectDuplicates=!!P;H();v.sortDetached=h(function(a){return a.compareDocumentPosition(z.createElement("div"))&1});h(function(a){a.innerHTML="<a href='#'></a>";
return"#"===a.firstChild.getAttribute("href")})||e("type|href|height|width",function(a,c,b){if(!b)return a.getAttribute(c,"type"===c.toLowerCase()?1:2)});(!v.attributes||!h(function(a){a.innerHTML="<input/>";a.firstChild.setAttribute("value","");return""===a.firstChild.getAttribute("value")}))&&e("value",function(a,c,b){if(!b&&"input"===a.nodeName.toLowerCase())return a.defaultValue});h(function(a){return null==a.getAttribute("disabled")})||e("checked|selected|async|autofocus|autoplay|controls|defer|disabled|hidden|ismap|loop|multiple|open|readonly|required|scoped",
function(a,c,b){var d;if(!b)return!0===a[c]?c.toLowerCase():(d=a.getAttributeNode(c))&&d.specified?d.value:null});"function"===typeof r&&r.amd?r(function(){return c}):"undefined"!==typeof module&&module.exports?module.exports=c:a.Sizzle=c})(window);b.browser=function(){var a,c={},d=navigator.userAgent.toLowerCase().replace(/\s*[()]\s*/g,"; ").replace(/(\/[\w.]+)\s+/g,"$1; ").replace(/\;\s*$/,"").split(/;\s*/);b.each(d,function(b){a=(/[\/ :]([^\/ :]+)$/.exec(b)||[])[1];c[a?b.substr(0,b.length-a.length-
1).replace(/\d*$/,""):b]=a||!0});return{aol:c.aol,blackberry:c.blackberry,ie:c.msie||c.trident,ios:c.mobile&&c.safari,opera:c.opera,playstation:c.playstation,version:parseFloat(c.version||c.crios||c.msie)||!1}}();b.harmony={PASSIVE:1,UNSAFE_QUIRKSMODE_EVENTS:0.5,COMMERCIAL_LINK_EVENTS:0.1,LINK_EVENTS:-1,AGGRESSIVE:-1};b.harmony.DEFAULT=0;b.pii=function(){var a={email:/[A-Z0-9._%+-]+(?:%(?:25)*40|@)[A-Z0-9.-]+\.[A-Z]{2,4}/,numeric:/\d([^0-9A-Z]{0,4}\d){6,18}/},c={contains:function(a,c){return this.regexp(c).test(a)},
redact:function(a,c){return a.replace(this.regexp(c),"___")},regexp:function(c){c=b.extend({},c);var f=b.map(b.all(a,function(a,b){return!1!==c[b]}),function(a){return a.source});return RegExp("(\\b"+f.join("\\b|\\b")+"\\b)","gi")},transmits:function(a,c){return this.contains(a+" "+document.referrer,c||{numeric:!1})}};return{contains:b.bind(c.contains,c),redact:b.bind(c.redact,c),transmits:b.bind(c.transmits,c)}}();b.platforms=function(){var a={NONE:{id:"full",scope:"body",spec:{selector:"body"}},
bbp:{spec:{parser:/^post-(\d+)$/,selector:"div[id^='post-']"},scope:"li .post"},hdlr:{spec:{parser:/^post_(\d+)$/,selector:"div[id^='post_']"},scope:".post-content-area"},ipb:{spec:{parser:/^post_id_(\d+)$/,selector:"div[id^='post_id_']"},scope:".post_body .post"},phpb:{spec:{parser:/^p(\d+)$/,selector:"div.post[id^='p']"},scope:".postbody .content,.postbody .signature"},ubb:{spec:{parser:/^number(\d+)$/,parse_el:"span[id^=number]",selector:"a[name^='Post'] ~ table"},scope:".post_inner *[id^='body'],.post_inner .signature"},
vb3:{spec:{parser:/^post_message_(\d+)$/,selector:"div[id^='post_message_'], table[id^='post_message_'],section[id^='post_message_']"},scope:"div[id^='post_message_'],div[id^='post_message_'] ~ div:not([class])"},vb4:{spec:{parser:/^post_(\d+)$/,selector:"li[id^='post_']"},scope:".post-content,.postbody .content,.postbody .signature,ul.conversation-list .list-item-body"},wppr:{spec:{attributes:["id","className"],parser:/(?:^|\s)post-(\d+)(?:\s|$)/,selector:"article[class*='post-'], div[id^='post-']"}}},
c={getPostId:function(a){var c,h;if(this===b.platforms.NONE)return" ";h=this.spec.parse_el?b.select(this.spec.parse_el,a)[0]:a;b.find(this.spec.attributes||["id"],b.bind(function(a){c=h[a]?h[a].match(this.spec.parser):null;return Boolean(c)},this));if(c)return c[1]},getPostIds:function(a){var c=[];b.each(this.getPosts(a),b.bind(function(a){(a=this.getPostId(a))&&!b.contains(c,a)&&c.push(a)},this));return c.length?c:null},getPosts:function(a){var c=[];!a&&(document&&document.body)&&(a=[document.body]);
a&&this.spec&&(c=b.unique(b.reduce([],b.withScope(a,this.spec.selector),function(a,c){return a.concat(c[1])})));return c}};b.each(a,function(d,f){d.id=d.id||f;b.each(c,function(a,c){d[c]=b.bind(a,d)});a[f]=d});a.DEFAULT_POST_ID=" ";a.findById=function(a){return b.find(b.platforms,function(c){return c.id===a})};return a}();b.observer=function(){var a=[],c=0,d=function(a){c||a.observer.observe(a.context.document,{attributes:!1,characterData:!0,childList:!0,subtree:!0})};return{start:function(c,h){if(c.document&&
b.traits.mutation){var e={context:c,observer:new MutationObserver(b.entryPoint(function(a){var c=[];b.each(a,function(a){var d=[];"characterData"===a.type?a.target&&(d=[a.target]):a.addedNodes&&a.addedNodes.length&&(d=b.toArray(a.addedNodes));d.length&&(c=c.concat(d))});0<c.length&&h(c)}))};a.push(e);d(e)}},pause:function(){c++;b.each(a,function(a){a.observer.disconnect()})},resume:function(){c--;b.each(a,d)}}}();b.traits={basicCompatibility:!(b.browser.blackberry||b.browser.playstation),cors:window.XMLHttpRequest&&
void 0!==(new window.XMLHttpRequest).withCredentials,crossWindowCommunication:!b.browser.ios,json:Boolean(window.JSON)&&Boolean(window.JSON.stringify)&&Boolean(window.JSON.parse),jsRedirectSetsReferrer:b.browser.aol||!(b.browser.ie||b.browser.opera),mutation:window.MutationObserver&&!b.browser.ie,performanceTiming:Boolean(window.performance&&window.performance.timing),quirksMode:!Boolean(window.addEventListener),windowLevelHandlers:Boolean(window.addEventListener)};var g,m,n,q;e={EVENT_LEVEL_LINK:1,
EVENT_LEVEL_TOP:2,PLUGIN_MANUAL:1,TYPE_ACCEPTABLE:"l",allowed:b.generateNodeFilter({classes:["norewrite"],rels:["norewrite"],tags:"applet embed object head img input link meta param select button iframe option script style svg textarea title".split(" ")}),api:function(){var a=function(){var a=function(a,c){a=b.fromJSON(a)||{};b.each(a,function(a,d){var f=c[d],h;if(f&&f.callback&&a){if("string"===b.type(a)&&(h=a.match(/^[^(]+\((.*)\);?\s*$/)))a=b.fromJSON(h[1]);f.callback.apply(window,[a].concat(f.data||
[]))}})};return function(d){var k={},g={};b.each(d,function(a){a=c.apply(this,a);var d=a.method;k[d]=b.prune(a.params);g[d]={callback:a.opts.fn||b.noop,data:a.data}});f({data:g,method:"batch",params:b.extend(e.commonParams(),{batch:window.JSON.stringify(k)}),opts:{jsonp:!1,fn:function(c,b){a(c,b)}}})}}(),c=function(a,c,f){var p=b.toArray(arguments).slice(3,arguments.length),n=a,m=d(f),q;q=b.extend(e.commonParams(a),c);q.subId&&q.key!==g.key&&(q.subId=null);return{data:p,method:n,opts:m,params:q}},
d=function(a){a=a||{};"function"===b.type(a.fn)&&(a.fn=function(c){return function(d){var f;"object"===b.type(d)&&("array"===b.type(d.crawl)&&"object"===b.type(q.crawler)&&"function"===b.type(q.crawler.crawl))&&(f=b.map(d.crawl,function(a){return a+""}),delete d.crawl,q.crawler.crawl(f));return c.apply(a,arguments)}}(a.fn));return a},f=function(a){return b.request.apply(b,[g.api_url+"/"+a.method,a.params,a.opts].concat(a.data))};return b.batchable(function(){return b.batched(arguments)?a.call(this,
b.batchArgs(arguments)):f(c.apply(this,arguments))},function(){return{batch:g.batch_calls,timeout:g.batch_call_timeout}})}(),addEventListener:function(a,c){this.fire(a,c)},click:function(){var a=function(a,c){if("_self"===c)return a;if(b.traits.crossWindowCommunication&&b.traits.jsRedirectSetsReferrer){var e=a.open("",c);e.focus();return e}},c=function(a){var c=a.previousSibling,h=a.nextSibling,g=["",a.textContent,""],k=function(a,c){for(var b=a,d=b.data;(b=b[c+"Sibling"])&&3===b.nodeType;)d+=b.data;
return d},p=function(a,c,b){a=a.replace(/\s+/g," ");c=c.replace(/\s+/g," ");b=b.replace(/\s+/g," ");a=a.replace(/^\s+/,"");" "===c.substr(0,1)&&(c=c.substr(1),a+=" "!==a.substr(a.length-1,1)?" ":"");" "===c.substr(c.length-1,1)&&(c=c.substr(0,c.length-1),b=(" "!==b.substr(0,1)?" ":"")+b);b=b.replace(/\s+$/,"");return[a,c,b]};void 0!==g[1]&&(g[0]=c&&3===c.nodeType?k(c,"previous"):"",g[2]=h&&3===h.nodeType?k(h,"next"):"",g=p.apply(this,g),""!==g[0]&&""!==g[2]&&(g[0]=g[0].split(" ").reverse().slice(0,
10+(" "===g[0].substr(g[0].length-1,1)?1:0)).reverse().join(" "),g[2]=g[2].split(" ").slice(0,10).join(" "),a={type:"context",itype:(b.cache(a,"params")||{}).type,before:g[0],after:g[2],txt:g[1],loc:location.href,out:b.getActualHref(a),v:2},e.log("info",b.toQuery(a))))};return function(d,f){var e,n,k,p,s=b.context(d)||window;f=d.target||f;f=!f||f===s.name||"_top"===f&&s.top===s||"_parent"===f&&s.parent===s?"_self":f;k=a(s,f);if("_self"!==f&&(!b.traits.crossWindowCommunication||!b.traits.jsRedirectSetsReferrer))p=
"go";else try{if(void 0===k.document)throw!0;p="jsonp"}catch(m){p="go"}e=b.destructing(b.bind(function(){g.time_api&&this.logEvent.stop("clk");var a=b.toArray(arguments);a.unshift(d,k,f);this.onApiClick.apply(this,a)},this));b.cache(this,"link","string"===typeof d?d:b.getActualHref(d));if("string"===typeof d&&(d=b.createA(d,f),!this.processLink(d))||!g.enabled)return e();n=this.clickParams(d,p);g.time_api&&this.logEvent.start("clk");g.log_context&&c(d);if("go"===p)this.redirect(this.api.now("click",
n,{"return":!0}),s,k,f);else if(k===s)this.api.now("click",n,{fn:e,timeout:g.click_timeout});else{if(b.contextIsAncestor(s,k))return this.redirect(b.getActualHref(d),s,k,f);e=b.entryPoint(e);setTimeout(function(){e()},g.click_timeout);k.document.open();k.callback=e;k.document.write("<html><head><title>"+b.getActualHref(d)+'</title><script type="text/javascript" src="'+this.api.now("click",n,{fn:"callback","return":!0})+'">\x3c/script></head></html>');k.document.close()}}}(),clickParams:function(a,
c){var d=b.extend(b.cache(a,"params"),{format:c,out:b.getActualHref(a),ref:window.document.referrer||null,reaf:g.reaffiliate||null,title:window.document.title,txt:a.innerHTML,loAsUuid:b.cache(a,"uuid")||null,rewrit:b.cache(a,"rewrit")});128<d.txt.length&&(d.txt=d.txt.replace(/<[^>]+>/g,""),d.txt=128<d.txt.length?d.txt.substr(0,125)+"...":d.txt);return d},commonParams:function(a){var c={drKey:g.key?null:g.dr_key,key:g.key,libId:g.library_id,subId:g.sub_id};("click"===a||"ping"===a)&&b.extend(c,{cuid:g.cuid,
loc:location.href,v:1},c);return c},detectFiltering:function(){var a;try{a={},a=new function(){this.detect=function(a,c){function b(a,c){0==g||1E3<c?a(0==g&&k):setTimeout(function(){b(a,2*c)},2*c)}function e(){--g||(k=!n&&m)}var k=!1,g=2,n=!1,m=!1;if("function"==typeof c){a+="?ch=*&rn=*";var q=11*Math.random(),l=new Image;l.onload=e;l.onerror=function(){n=!0;e()};l.src=a.replace(/\*/,1).replace(/\*/,q);l=new Image;l.onload=e;l.onerror=function(){m=!0;e()};l.src=a.replace(/\*/,2).replace(/\*/,q);b(c,
250)}}}}catch(c){a={detect:function(a,c){c(!0)}}}return function(c){var f=b.updateUrl(g.asset_url,{pathname:"/images/pixel.gif"});a.detect(f,c)}}(),enabled:function(){if(g.enabled&&n!==window&&window.vglnk&&(window.vglnk.key||"function"===typeof window.vglnk))g.enabled=!1;return g.enabled},expose:function(){return function(a,c){if((c=c||this[a])&&!q[a]){var d=q,f;f=c;f="function"===b.type(f)?b.entryPoint(b.bind(f,e)):f;d[a]=f}}}(),fire:function(){var a={};return function(c,d){c=c.toLowerCase();var f=
a[c]||{fired:!1,listeners:[]};"function"===typeof d?f.fired?setTimeout(function(){d({type:c})},0):f.listeners.push(d):(f.fired=!0,b.each(f.listeners,function(a){"function"===typeof a&&a({type:c})}),f.listeners=[]);a[c]=f}}(),handleRightClick:function(a,c){if(g.rewrite_modified&&a&&c)switch(c){case "setup":b.cache(a,"href")||b.cache(a,"href",a.href);a.href=this.api.now("click",this.clickParams(a,"go"),{"return":!0});setTimeout(b.entryPoint(b.bind(function(){this.handleRightClick(a,"teardown")},this)),
0);break;case "teardown":b.cache(a,"href")&&(a.href=b.cache(a,"href"))}},harmony:function(a){return g.harmony_level<=a},init:function(){var a=function(){var a=!0===window.document.__v5k;window.document.__v5k=!0;return!a};return function(){var c=this;m={};if(a()){try{c.initLibEvents(),c.initNamespace(),c.initOptions()}catch(d){}b.exceptionLogger(b.bind(c.logException,c),!g.dev);b.each(g.script_timeout);return b.entryPoint(function(){c.initProcessors();c.initDRApi();c.initApi();c.enabled()&&(c.initLegacyCallbacks(),
c.ping())})()}}}(),initApi:function(){var a,c={};if(window.vglnk)for(a in window.vglnk)"_plugin"===a.substr(-7)&&(c[a]=window.vglnk[a]);q=n[l]=b.noop;this.expose("click");this.expose("link",b.bind(function(a){"element"===b.type(a)&&a.href&&(this.initContext(b.context(a)),this.processLink(a))},this));this.expose("open",b.bind(this.click,this));this.expose("$",b.clone(b));this.expose("api");this.expose("api_now",b.bind(this.api.now,this.api));this.expose("harmony");this.expose("opt");this.expose("platform");
this.expose("registerProcessor",function(){if(0<arguments.length)return e.registerProcessor.apply(e,arguments)});b.extend(q,q===window.vglnk?c:{})},initContext:function(){var a=[];return function(c){if(void 0===c)return a;c&&!b.contains(a,c)&&(a.push(c),this.initLinks(c),this.initEvents(c))}}(),initDRApi:function(){var a=!1;window.DrivingRevenue=b.entryPoint(b.destructing(b.bind(function(){a=!0;g.dr_key=window.DR_id;this.enabled()&&this.ping()},this)));b.on("DOMReady",function(){if(!a)try{delete window.DrivingRevenue}catch(c){window.DrivingRevenue=
void 0}})},initEvents:function(a){var c=b.traits.windowLevelHandlers?a:a.document,d=function(c){c=c||a.event;if((c=b.eventLink(c))&&!b.cache(c,"evented"))n(e.EVENT_LEVEL_LINK,c),b.cache(c,"evented",!0)},f=function(a){b.observer.start(a,b.batchable(function(a){b.batched(arguments)&&(a=b.reduce([],b.batchArgs(arguments,0),function(a,c){return a.concat(c)}));a=b.all(b.unique(a),function(a){return Boolean(a.parentNode)&&e.allowed(a)});0<a.length&&(b.each(b.withScope(a,"a[href]",{ancestors:!1}),function(a){e.processLinks(a[1])}),
b.each(m,function(c,b){c.opts.mode!==e.PLUGIN_MANUAL&&e.runPlugin(b,a)}))},function(){return{batch:g.batch_mutation,timeout:g.batch_mutation_timeout}}))},h=function(a,c){return function(){var d=[a].concat(b.toArray(arguments));c.apply(e,d)}},n=function(a,c){b.on(c,"click",h(a,e.onClick));b.on(c,"contextmenu",h(a,e.onContextmenu))};if(g.dynamic)b.on("DOMReady",function(){f(a)});b.on(c,"copy",b.bind(e.onCopy,e));b.on(c,"mousedown",d);b.on("DOMReady",function(){b.each(a.document.links,function(a){b.on(a,
"mousedown",d)})});(!b.traits.quirksMode||e.harmony(b.harmony.UNSAFE_QUIRKSMODE_EVENTS))&&n(e.EVENT_LEVEL_TOP,c)},initLegacyOptions:function(){var a,c={DR_id:"dr_key",vglnk_api_key:"key",vglnk_cuid:"cuid",vglnk_domain:"api_url",vglnk_reaf:"reaffiliate",vglnk_subid:"sub_id"};for(a in c)void 0!==window[a]&&(q[c[a]]=window[a],"vglnk_domain"===a&&(q[c[a]]+="/api"))},initLegacyCallbacks:function(){var a,c={vl_cB:b.bind(this.onApiClick,this),vl_disable:function(){g.enabled=!1}};for(a in c)window[a]=c[a]},
initLibEvents:function(){b.on(e);b.ready(b.bind(function(){this.fire("DOMReady")},this))},initLinks:function(a){var c=b.bind(function(a){this.processLinks(b.toArray(a.document.links))},this);void 0===a?b.each(this.initContext(),c):c(a)},initNamespace:function(){window.vglnk&&window.vglnk.key&&(l="vglnk");var a=window,c=l.split("."),b;for(l=c.pop();0<c.length;)b=c.shift(),a[b]=a[b]||{},a=a[b];n=a;q=n[l]=n[l]||{}},initOptions:function(){var a;this.initLegacyOptions();g=b.extend(this.publicOptions({api_url:"//api.viglink.com/api",
asset_url:"//cdn.viglink.com/api",cuid:null,dev:!1,dr_key:null,enabled:b.traits.basicCompatibility,key:null,link_urls:!0,partner:null,platform:b.platforms.NONE.id,sub_id:null,reaffiliate:!1,commercial:null,harmony_level:b.harmony.DEFAULT,link_target:null,rewrite_any:!0,rewrite_modified:!1,rewrite_original:!0}),g,q,{batch_calls:!0,batch_call_timeout:100,batch_mutation:!0,batch_mutation_timeout:250,click_timeout:1E3,dynamic:!0,hop_timeout:2E3,debug:!1,library_id:null,log_context:!0,nofollow:{},norewrite:{},
script_timeout:2E3,time_log_timeout:3E3,time_api:!1,time_load:!1,testing_js:[],plugins:{crawler:{},harmony:{},link_affiliation:{},modified_clicks:{}}});for(a in g)"_plugin"===a.substr(-7)&&delete g[a]},initPlugins:function(){var a,c=1,d={link_affiliation:"convert",link_optimization:"optimize",page_harmony:"harmony",partner_integration:"partners",product_linker:"insert",product_widget:"spotlight"},f=["spotlight"],h=["harmony"],n=function(b){return function(b){return function(){delete m[b].opts.mode;
c=1;clearTimeout(a);p()}}(b)},k=function(a){var c;b.find(d,function(a,b){return"insert"===a&&(c=b)});a[c]||(a[c]={enabled:!0,key:g.key,link_phrases:!1});a[c].link_urls=g.link_urls;return a},p=function(){var d={_ran:!1,init:b.noop,initDocuments:b.noop,initNodes:b.noop,"public":{}},f=function(a,c){a.setup=a.setup||(window.vglnk?window.vglnk[c+"_plugin"]:null);"function"===b.type(a.setup)&&(Boolean(a.initDocuments)||(a=b.extend(a,d,a.setup(a.opts,b.clone(b),q,k(g.key))),a["public"]&&e.expose(c,a["public"],
!1)),a.opts.mode!==e.PLUGIN_MANUAL&&e.runPlugin(c))},k=function(a){var c=function(){if(a){var c=b.toArray(arguments);c.unshift("custom",a);e.log.apply(this,c)}};c.event=e.logEvent;return c},n=function(a){return!Boolean(a._ran)};a=null;b.each(h,function(a){var c=m[a];c&&!Boolean(c._ran)&&f(c,a)});b.each(b.all(m,n),f);b.find(m,n)&&(a=setTimeout(b.entryPoint(p),Math.min(Math.max(Math.pow(2,++c),100),5E3)))},s=function(){setTimeout(function(){e.api.flush()},100);p();b.on("DOMReady",function(){setTimeout(e.api.flush,
0)})};return function(a){a=k(a);b.each(a,b.bind(function(a,c){c=d[c]||c;"object"===typeof a&&!1!==a.enabled&&(m[c]={opts:a},b.contains(f,c)&&b.jsonp(this.opt("asset_url")+"/plugins/"+c+".js"),a.mode===this.PLUGIN_MANUAL&&this.expose("init_"+c,n(c)))},this));s()}}(),initProcessors:function(){this.registerProcessor(function(a){var c;c=b.createA(g.api_url);if("/api/click"===a.pathname&&(a.hostname===c.hostname||a.hostname.match(/(^|\.)(api|cdn|apicdn)\.viglink\.com$/)))c=b.fromQuery(a.search),void 0!==
c.out&&(a.href=c.out,delete c.out,b.cache(a,"params",c))});this.registerProcessor(function(a){g.nofollow[a.href]&&!b.hasRel(a,"nofollow")&&(a.rel=(a.rel?a.rel+" ":"")+"nofollow")});this.registerProcessor(function(a){window.IPBoard&&(window.IPBoard.prototype&&window.IPBoard.prototype.delegate&&b.hasRel(a,"external"))&&(a.rel=a.rel.replace(/(^| )external( |$)/,""),a.target="_blank")})},isCommercial:function(a){a=b.canonicalizeHostname(a);return"object"===b.type(g.commercial)&&g.commercial[a]},isRewritable:function(){var a=
b.canonicalizeHostname(document.location),c=b.generateNodeFilter({rels:["noskim"],custom:function(c){var f=b.canonicalizeHostname(c),h="",n=!1;try{h=c.protocol,f.charAt(0)}catch(k){return!0}n=Boolean(""===f||!h.match(/^https?:$/i)||g.norewrite[f]);if(h=!n)var h=b.cache(c,"type"),p=b.cache(c,"params")||{},h=!Boolean(h||p.type);h&&(n=Boolean(a===f||!g.rewrite_original||!g.rewrite_any&&!e.isCommercial(c)));return n}});return function(a){return this.allowed(a)&&c(a,{ancestors:!1})}}(),log:function(a,
c,d,f){var e,n=b.toQuery({libId:g.library_id,nocache:b.uniqid()});e="pixel.gif";if("custom"===a)n+="&"+b.toQuery({key:c,type:d}),b.each("array"===b.type(f)?f:[f],function(a){b.each(["e","i","o"],function(c){delete a[c]});n+="&"+b.toQuery(a)});else{n+="&"+b.toQuery({key:g.key,drKey:g.key?null:g.dr_key,subId:g.sub_id});if("time"===a&&b.traits.json)e="time.gif",a={e:b.toJSON(c),v:2};else if("exception"===a)a={e:c,o:d};else if("info"===a)a={i:c};else return;n+="&"+b.toQuery(a)}e=g.api_url+"/"+e+"?"+n;
b.pii.transmits(e)||(b.createEl("img").src=e)},logEvent:function(){var a={},c=b.time(),d=b.traits.performanceTiming?window.performance.timing.domLoading:null,f=b.batchable(function(){var a;a=b.batched(arguments)?b.batchArgs(arguments):[arguments];a=b.map(a,function(a){return b.prune({event:a[0],time:a[1],total:a[2]})});a.length&&e.log("time",a)},function(){return{timeout:g.time_log_timeout}});return{start:function(c){a[c]=a[c]||{logged:0,times:[]};a[c].times.push(b.time())},stop:function(c){var e,
g,n=b.time();a[c]&&(a[c].times&&a[c].times.length)&&(e=a[c].times.shift(),g=d&&0===a[c].logged?n-d:null,a[c].logged+=1,f(c,n-e,g))},load:function(){d&&f("load",c-d)}}}(),logException:function(a){if(g.debug){var c={link:b.cache(this,"link"),loc:document.location.href,UA:navigator.userAgent};"string"===typeof a?c.message=a:c=b.extend(c,a);this.log("exception",a,b.toQuery(c))}},onApiClick:function(a,c,d,f,e){var n=f||b.getActualHref(a),k=b.bind(function(){this.redirect(n,b.context(a),c,d)},this);"object"===
typeof e&&(e.tracking||e.image)?(f=b.createEl(e.tracking?"iframe":"img",{src:e.tracking||e.image},{height:0,width:0,visibility:"hidden"}),document.body.appendChild(f),setTimeout(b.entryPoint(k),e.timeout||g.hop_timeout)):k()},onApiPing:function(a,c,d,f,h,n){g.rewrite_original=!1;h=b.reformatKeys(h||{});var k,p;f=function(a){var c={},d=function(a){b.isArray(a)?c[a[0]]=a[1]:c[a]=1};b.isArray(a)&&b.each(a,d);return c};p=b.extend(g.plugins,h.plugins);g=b.extend(g,h);delete g.plugins;g.click_timeout=c;
g.library_id=a;h.time&&(g.time_api=g.time_load=h.time);g.time_api&&this.logEvent.stop("png");g.time_load&&this.logEvent.load();"array"===b.type(g.testing_js)&&0<g.testing_js.length&&b.each(g.testing_js,function(a){b.jsonp(a)});b.extend(g.nofollow,f(n));b.extend(g.norewrite,f(d));for(k in g)"on"===k.toLowerCase().substr(0,2)&&(2<k.length&&"function"===b.type(g[k]))&&(b.on(e,k.toLowerCase().substr(2),b.bind(g[k],window)),delete g[k]);this.initPlugins(p);this.initContext(window);this.fire("libready")},
onClick:function(a,c){c=c||window.event;var d=c.ctrlKey||c.metaKey||c.altKey||c.shiftKey,e=c.which&&1===c.which||0===c.button,h=b.eventLink(c);if(h&&e&&!d&&!b.isDefaultPrevented(c)&&this.isRewritable(h)&&this.shouldHandleClick(a,h))return this.click(h),b.preventDefault(c)},onContextmenu:function(a,c){var d=b.eventLink(c||window.event);d&&(this.isRewritable(d)&&this.shouldHandleClick(a,d))&&this.handleRightClick(d,"setup")},onCopy:function(a){var c,d,f,h=[];if(window.getSelection){d=window.getSelection();
a=0;for(c=d.rangeCount;a<c;a++){try{f=d.getRangeAt(a).toString().replace(/((^)\s+|\s+$|\r)/g,"").replace(/\s*\n\s*/g,"\n")}catch(g){}0<f.length&&128>=f.length&&h.push(f)}}b.each(h,function(a){e.log("info",b.toQuery({type:"selection",txt:a,loc:location.href}))})},opt:function(a,c){void 0!==c&&void 0!==this.publicOptions()[a]&&(g[a]=c);return g[a]},ping:function(){var a=!1;return function(){if(!a&&(g.key||g.dr_key)){var c={ref:document.referrer||null};a=!0;b.pii.transmits(this.api.now("ping",c,{"return":!0}))||
(this.logEvent.start("png"),this.detectFiltering(b.bind(function(a){a&&(g.batch_calls=!1,c.type=this.TYPE_ACCEPTABLE);this.api.now("ping",c,{fn:b.bind(this.onApiPing,this)})},this)))}}}(),platform:function(){return b.platforms.findById(g.platform)||b.platforms.NONE},processLink:function(a){var c=b.cache(a,"processors")||{},d=this.isRewritable(a);b.each(this.registerProcessor(),function(b){!c[b.id]&&(d||b.opts.any)&&b.fn(a);c[b.id]=!0});b.cache(a,"processors",c);return a},processLinks:function(a){b.each(a,
b.bind(this.processLink,this))},publicOptions:function(){var a={};return function(c){"object"===b.type(c)&&(a=c);return b.extend({},a)}}(),redirect:function(a,c,d,e){c=c||window.top;!b.traits.crossWindowCommunication&&!d?(e=c.open(a,e),e.focus()):b.traits.jsRedirectSetsReferrer?setTimeout(b.entryPoint(function(){!d||d===c?c.location=a:b.contextIsAncestor(c,d)?d.location=a:d.location.replace(a)}),0):("_blank"===e&&(e=b.uniqid("win_")),e=b.createA(a,e),e.rel="norewrite",c.document.body.appendChild(e),
e.click(),e.parentNode.removeChild(e))},runPlugin:function(a,c){var d=window.document,e=m[a];if(e&&e.initDocuments){if(c)e.initNodes(c);else if(e.init(),"function"===b.type(e.initDocuments)&&"document"===b.type(d)&&e.initDocuments([d]),"function"===b.type(e.initNodes)&&"element"===b.type(d.body))b.on("DOMReady",function(){e.initNodes([d.body])});e._ran=!0}},registerProcessor:function(){var a=!1,c=[],d=function(d,e){if(void 0===d)return c;"function"===b.type(d)&&(e=b.extend({any:!1},e),c.push({fn:d,
id:b.uniqid(),opts:e}),a&&this.initLinks())};d(function(){a=!0});return d}(),shouldHandleClick:function(a,c){var d=!0;a===this.EVENT_LEVEL_LINK&&(d=this.harmony(b.harmony.LINK_EVENTS)||this.isCommercial(c)&&this.harmony(b.harmony.COMMERCIAL_LINK_EVENTS));return d}};e.init();try{delete window.vglnk_self}catch(u){}})("undefined"===typeof vglnk_self?"vglnk":vglnk_self);window.vglnk=window.vglnk||{};
window.vglnk.convert_plugin=function(l,e,b){var r={},g,m;l=e.extend({any:!0,convert_minimum_bid:!1},l);m={getDomains:function(){var g=[];e.each(r,function(b,e){2!==r[e]&&(g.push(e),r[e]=2)});0<g.length&&b.api("domains",{domains:g.join("|"),v:"2"},{fn:e.bind(m.onDomainApi,m)})},init:function(){b.opt("link_target",l.link_target);b.opt("rewrite_any",l.any);b.opt("rewrite_original",!0);(g=!l.any||b.harmony(e.harmony.COMMERCIAL_LINK_EVENTS)||l.convert_minimum_bid)&&b.registerProcessor(e.bind(function(b){this.initDomainLookup();
this.saveDomain(b)},this),{any:!0})},initDomainLookup:function(){var b=!1;return function(){b||(b=!0,e.on("DOMReady",e.bind(this.getDomains,this)))}}(),onDomainApi:function(g){var m;"object"===e.type(g)&&"array"===e.type(g.results)?(m=b.opt("commercial")||{},e.each(g.results,function(b){m[b]=!0}),b.opt("commercial",m)):"object"===e.type(g)&&"object"===e.type(g.results)&&(m=b.opt("commercial")||{},e.each(g.results,function(b,a){m[a]=b.unlink?!1:!0}),b.opt("commercial",m),b.registerProcessor(e.bind(function(b){this.minimumBidUnlink(b)},
this),{any:!0}))},saveDomain:function(b){b=e.canonicalizeHostname(b);r[b]=r[b]||1},minimumBidUnlink:function(g){var m=e.canonicalizeHostname(g);!1===(b.opt("commercial")||{})[m]&&e.unlink(g)}};return{init:e.bind(m.init,m),initNodes:function(){g&&m.getDomains()}}};window.vglnk=window.vglnk||{};
window.vglnk.crawler_plugin=function(l,e,b){var r=[],g=b.platform();l={crawl:function(b){if(g&&!("array"!==e.type(b)||0===b.length))b=e.all(b,function(b){return!e.contains(r,b)}),b=this.findPostsById(b),e.each(b,e.bind(function(b){b.content=this.redact(b.el.innerHTML.replace(/(^\s+|\s+$)/g,""));delete b.el},this)),b=e.all(b,function(b){return Boolean(b.content&&b.id)}),0<b.length&&this.processPosts(b)},findPostsById:function(b){return e.all(e.map(g.getPosts(),function(b){return{el:b,id:g.getPostId(b)}}),
function(g){return e.contains(b,g.id)})},processPosts:function(m){m=e.map(m,function(b){r.push(b.id);return{c:b.content,i:b.id}});b.api("content",{content:e.toJSON({ct:m,pt:g.id,u:location.href})},{jsonp:!1,ssl:b.opt("dev")?!1:!0})},redact:function(b){return e.pii.redact(b)}};return{"public":{crawl:e.bind(l.crawl,l)}}};window.vglnk=window.vglnk||{};window.vglnk.modified_clicks_plugin=function(l,e,b){return{init:function(){b.opt("rewrite_modified",!0)}}};window.vglnk=window.vglnk||{};
window.vglnk.dr_search_box_plugin=function(l,e,b){l=e.extend({key:null},l);var r={init:function(b){e.each(this.getDRSearchForms(b),function(b){if(!e.cache(b,"evented")){var g=r.getInput(b),l=function(){g.value||e.css(g,{"background-image":"url(http://cdn.viglink.com/images/ebay_watermark.gif)"})};e.cache(b,"evented",!0);b.onsubmit=null;g.onfocus=null;g.onblur=null;e.on(g,"focus",function(){e.css(g,{"background-image":"none"})});e.on(g,"blur",l);l();e.on(b,"submit",function(e){r.onSubmit(e,b)})}})},
getDRSearchForms:function(b){var m=[];e.each(b,function(b){"element"===e.type(b)&&e.each(b.getElementsByTagName("form"),function(b){r.getInput(b)&&b.id.match(/^DR-ebay-search(CSS|2)?$/i)&&m.push(b)})});return m},getInput:function(b){return b.p||b.q2},onSubmit:function(g,m){g=g||window.event;var n="http://shop.ebay.com/i.html?"+e.toQuery({_nkw:r.getInput(m).value}),n=e.createA(n,"_blank");e.cache(n,"params",{key:l.key});b.click(n);return e.preventDefault(g)}};if(l.key)return{init:e.bind(r.init,r),
initNodes:function(b){r.init(b)}}};window.vglnk=window.vglnk||{};window.vglnk.harmony_plugin=function(l,e,b){l=e.extend({level:e.harmony.DEFAULT},l);return{init:function(){var e=parseFloat(l.level,10);isFinite(e)&&b.opt("harmony_level",e)}}};window.vglnk=window.vglnk||{};
window.vglnk.optimize_plugin=function(l,e,b,r){var g,m={uuid:"uuid",index:"idx",optimized_url:"url",aliases:"aka"};g={cache:function(){var b={},e={};return{links:{get:function(e){return b[e]},set:function(e,a){var c={};c[m.optimized_url]=a[m.optimized_url];c[m.uuid]=a[m.uuid];c[m.aliases]=a[m.aliases];b[e]=c}},stats:{increment:function(b,a){e[b]||(e[b]={});if(a)if("rep"===a)e[b].rep=(e[b].rep||0)+1;else{var c;c=e[b].ex=e[b].ex||{};c[a]=(c[a]||0)+1}else e[b].n=(e[b][m.insertion_count]||0)+1},getAndReset:function(){var b=
e;e={};return b}}}}(),filterLinkNodes:function(){var b={sameDomainOrInternal:function(){var b=window.location.hostname;return function(a){return b===a.hostname}}()},l=function(g){return e.all(g,function(a){return e.every(b,function(c){return!c(a)})})};return function(b){var a={needs_optimization:[],needs_call:[]};e.each(l(b),function(c){var b=g.cache.links.get(c.href);b&&b[m.uuid]&&e.cache(c,"uuid",b[m.uuid]);b&&b[m.optimized_url]?a.needs_optimization.push(c):b&&"false"===b[m.optimized_url]||a.needs_call.push(c)});
return a}}(),generateAliases:function(b){var l=g.cache.links.get(b.href),u=[],u=u.concat(l[m.aliases]||[]);u.push(e.canonicalizeHostname(b.href));u.push(e.canonicalizeHostname(l[m.optimized_url]));return e.unique(u)},getLinks:function(){var n=function(b){var g=[];e.each(b,function(a){g.push(a.href)});return g};return function(l){b.opt("time_api")&&r.event.start("opt");var m=e.unique(n(l));b.api_now("optimize",{links:m,u:location.href,ver:2},{fn:e.bind(g.onOptimizeApi,g)},m,l)}}(),log:e.batchable(function(){var b=
{stats:e.toJSON(g.cache.stats.getAndReset())};4<b.stats.length&&r("loJsLog",b)},function(){return{timeout:1E3}}),onOptimizeApi:function(n,l,u){b.opt("time_api")&&r.event.stop("opt");"object"===e.type(n)&&(e.each(["opt","non","unk"],function(a){n[a]&&n[a].length&&e.each(n[a],function(c){var b=l[c[m.index]];"non"===a&&(c[m.optimized_url]=!1);g.cache.links.set(b,c)})}),u=g.filterLinkNodes(u),g.optimizeLinks(u.needs_optimization))},optimizeLinks:function(b){e.each(b,function(b){e.cache(b,"rewrit",!1)});
b=g.runExclusionFilters(b);e.each(b,this.optimizeLink);e.traits.json&&g.log()},optimizeLink:function(){var b=function(a){return a.replace(/^https?:\/\//,"")},q=function(a,c){for(var b;b=a.firstChild;)a.removeChild(b);a.appendChild(document.createTextNode(c))},r=function(a){var c=a.href,d=a.textContent||a.innerText,f=Boolean(d),h=g.generateAliases(a),l=function(){var a=b(c).toLowerCase(),f=d.toLowerCase().replace(a,"");return e.some(h,function(a){return-1!==f.indexOf(a.toLowerCase())})},k=function(){var a=
d.split(/(?:\.\.\.|\u2026)/);return 2>a.length?!1:RegExp("^"+e.map(a,e.escapeRegExp).join(".+")+"$").test(c)},p=function(){var c=e.canonicalizeHostname(a);return e.canonicalizeHostname(e.createEl("a",{href:d}))===c},m=function(){var c;return p()?(c=e.fromQuery(a.search),e.find(c,function(a){return a===d})):!1};return{full_replace:Boolean(f&&(c===d||b(c)===d||k()||m())),exclude:Boolean(f&&l()),partial_replace:Boolean(f&&(-1!==d.indexOf(c)||-1!==d.indexOf(b(c))))}};return function(a){var c,d=g.cache.links.get(a.href),
f=d[m.optimized_url];c=r(a);if(f&&!l.observer){if(c.full_replace)q(a,f),g.cache.stats.increment(d[m.uuid],"rep");else{if(c.exclude){g.cache.stats.increment(d[m.uuid],"a");return}c.partial_replace&&(c="undefined"!==e.type(a.textContent)?a.textContent:a.innerText,c=-1!==c.indexOf(a.href)?c.replace(a.href,f):c.replace(b(a.href),f),q(a,c),g.cache.stats.increment(d[m.uuid],"rep"))}f=-1===f.indexOf("http://")?"http://"+f:f;a.href=f}g.cache.stats.increment(d[m.uuid]);e.cache(a,"rewrit",!0)}}(),runExclusionFilters:function(){var b=
e.generateNodeFilter({classes:["nooptimize","norewrite"],rels:["nooptimize","norewrite","noskim"],custom:function(a,c){if(c)return Boolean(e.cache(a,"type"))}}),l=function(a){var c=g.generateAliases(a),b=e.context(a).document.title;return e.every(c,function(a){return-1===b.indexOf(a)})},r=function(){var a=function(a,c){var b=e.reduce([],["prev_tokens","next_tokens"],function(c,b){a[b]&&a[b].length&&(c=c.concat(a[b]));return c}).join(" ").toLowerCase();return e.some(c,function(a){return-1!==b.indexOf(a.toLowerCase())})},
c=function(){var a=function(a){a="undefined"!==e.type(a.textContent)?a.textContent:a.innerText;return e.all(a.split(/\s+/g),function(a){return""!==a})};return function(c){for(var b={prev_tokens:[],next_tokens:[]};c&&c!==document.body.parentNode;){for(var g=b,k=c.previousSibling,p=c.nextSibling;k||p;)k&&(e.nodesOfType([k],1,3).length&&"SCRIPT"!==k.tagName)&&(g.prev_tokens=g.prev_tokens.concat(a(k).reverse())),k=!k?!1:k.previousSibling,p&&(e.nodesOfType([p],1,3).length&&"SCRIPT"!==p.tagName)&&(g.next_tokens=
g.next_tokens.concat(a(p))),p=!p?!1:p.nextSibling;if(20<b.prev_tokens.length+b.next_tokens.length+0)break;c=c.parentNode}return b}}();return function(b){var e=g.generateAliases(b);b=c(b);80<b.prev_tokens.length+b.next_tokens.length+0&&(b.prev_tokens=b.prev_tokens.slice(0,40),b.next_tokens=b.next_tokens.slice(0,40));b.prev_tokens=b.prev_tokens.reverse();return!a(b,e)}}();return function(a){return e.all(a,function(a){var d=g.cache.links.get(a.href)[m.uuid];if(b(a))if(r(a)){if(!l(a))return g.cache.stats.increment(d,
"t"),!1}else return g.cache.stats.increment(d,"p"),!1;else return g.cache.stats.increment(d,"n"),!1;return!0})}}()};return{initNodes:function(b){var l;b=e.nodesOfType(b,1);b=e.withScope(b,"a[href]",{ancestors:!1,consolidate:!0});b=g.filterLinkNodes(b);(l=b.needs_optimization)&&l.length&&g.optimizeLinks(l);(b=b.needs_call)&&b.length&&g.getLinks(b)}}};window.vglnk=window.vglnk||{};
window.vglnk.insert_plugin=function(l,e,b,r){var g,m,n,q,u=null,a=null;l=e.extend({cat:null,dynamic_sample_rate:1,key:null,link_phrases:!0,link_target:null,link_urls:!0,manual_mode:1===l.mode,per_page:null,per_phrase:5,proximity:null,same_proximity:100,scope:null,ui:!0},l);if(l.key)return g=b.platform(),m={cache:function(){var a={},b={},f=function(f,h){var g={};e.isArray(h)&&0<h.length&&e.find(h,function(a){var c=b;if(c[a]){if(f)return g[f]=c[a][f],!0;e.each(c[a],function(a,b){g[b]||(g[b]=a)})}});
g=e.extend(e.clone(a),g);return f?g[f]:g},h=function(f,h,g){(g=e.isArray(g)&&0<g.length?g:null)&&e.each(g,function(a){var c=b;c[a]=c[a]||{};"L"!==h.type&&(c[a][f]||(c[a][f]=h))});if(!g||"L"===h.type)a[f]||(a[f]=h);return!0},g=function(a,b,c){var d=e.all(e.toArray(arguments),function(a){return Boolean(a)});"array"===e.type(d[d.length-1])&&(c=d.pop());a=d[0];b=d[1];if(1>=d.length)return f(a,c);if(2===d.length)return h(a,b,c)};l.manual_mode&&e.extend(g,{reset:function(){a={};b={}}});return g}(),focusLink:function(a){a.id||
(a.id=e.uniqid("vl-link-"));location.href.hash="#"+a.id;window.scrollBy(0,-150)},getPartnerParams:function(){var a,d,e=b.opt("partner"),h={};for(a in e)break;if(a)for(d in e[a])h[a+"_"+d]=e[a][d];return h},getPhrases:function(a,d){b.opt("time_api")&&r.event.start("ins");b.api("insert",e.extend(m.getPartnerParams(),{cat:l.cat,i:d?d.join("|"):null,mode:l.mode,pt:g.id,ps:l.product_source,u:location.href}),{fn:e.bind(m.onInsertApi,m)},a,d)},hasCalled:function(){var a={},b=Math.random()<l.dynamic_sample_rate,
f=function(a){return b&&e.isArray(a)?e.map(a,function(a){return f(a)}):b&&a===e.platforms.DEFAULT_POST_ID?location.href:a},h=function(b){b=f(b);return e.isArray(b)&&b.length?Boolean(e.all(b,function(b){return a[b]}).length===b.length):Boolean(a[e.platforms.DEFAULT_POST_ID])},g=function(b){b=f(b);e.isArray(b)&&b.length?e.each(b,function(b){a[b]=!0}):a[e.platforms.DEFAULT_POST_ID]=!0};return function(a,b){return b?g(a):h(a)}}(),init:function(){l.scope=l.scope||g.scope;l.link_urls&&(q=RegExp("(?:(?:\\b(https?://)|(?:^|\\s)\\W*(www\\d{0,3}\\.|(?:[a-z0-9-]+\\.)+[a-z]{2,4}/))((?:[^\\s()<>]+|\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\))+(?:\\((?:[^\\s()<>]|(?:\\([^\\s()<>]+\\)))*\\)|[^\\s`!()\\[\\]{};:'\".,<>?\u00ab\u00bb\u201c\u201d\u2018\u2019]))|(?:^|\\s)\\W*((?:[a-z0-9-]+\\.)+com(?:/|\\b)))",
"i"))},initLink:function(a,d,f){var h=l.link_target;if(h="U"===d.type?b.opt("link_target"):h||f)a.target=h;a.href||(a.href=d.url);a.rel="nofollow";e.cache(a,"params",{exp:u,key:l.key,mid:d.mid,type:d.type||null});e.cache(a,"href",a.href);b.link(a)},insertLinks:function(){var a,b=e.generateNodeFilter({classes:["nolinks","atma-nolink","atma-nolinks"],tags:"applet embed object head img input link map meta param select button iframe option script style svg textarea title".split(" "),custom:function(a){return e.matches(a,
"a")&&Boolean(a.href)}}),f=function(a,c,e,g){if(b(c,{ancestors:!Boolean(g),self:!0}))if(3===c.nodeType)h(a,c,e);else if(1===c.nodeType)for(c=c.firstChild;c;)g=c.nextSibling,f(a,c,e,!0),c=g},h=function(a,b,c){var d=!1,e=b.parentNode,f=function(a,b){e.insertBefore(a,b);e.removeChild(b)};e&&(b.data&&(d=a.test(b.data.replace(/\s+/," "))),d&&g(a,b,c,f))},g=function(b,d,f,h){for(var g,n,q,r,w=function(b){var d;b=!b||!l.per_phrase||!a[b.phrase]||a[b.phrase].count<l.per_phrase;d=!l.per_page||e.reduce(0,a,
function(a,b){return a+b.count})<l.per_page;return b&&d},u=function(a,b,c){var d,f,h;if(!c.phrase)return!0;f=e.createEl("span");b.parentNode.insertBefore(f,b);f.appendChild(b);h=e.geometry(f);(l.proximity||l.same_proximity)&&e.find(m.cache(a),function(a){var b,f;if(a.links){if((b=m.normalizePhrase(a.phrase)===m.normalizePhrase(c.phrase))&&!l.same_proximity||!b&&!l.proximity)return!1;f=b?Math.max(l.same_proximity,l.proximity):l.proximity;a.links=e.all(a.links,function(a){var b=e.isInDom(a.el);!d&&
b&&(d=e.find(a.segments,function(a){a=a.geometry;a=e.extend({},a);a.x1-=f;a.y1-=f;a.x2+=f;a.y2+=f;if(a.x1<h.x2&&a.x2>h.x1&&a.y1<h.y2&&a.y2>h.y1)return!0}));return b});return d}});return function(a){f.parentNode.insertBefore(b,f);f.parentNode.removeChild(f);return a}(!d)},T=function(a,b){var c,d,f,h,g={el:a,segments:[]},k=a.getElementsByTagName("span"),l={els:[]};c=0;for(d=k.length;c<d;c++)f=k[c],void 0===h||f.offsetTop===h.offsetTop?l.els.push(f):(g.segments.push(l),l={els:[f]}),h=f;l.geometry=e.geometry.apply(e,
l.els);g.segments.push(l);b.links=b.links||[];b.links.push(g);return b};d&&d.data&&""!==d.data&&(Boolean(q=d.data.match(/^\s+/))||Boolean(q=d.data.match(b)));)n=q[0],r=q.slice(1).join(""),g=(g=m.normalizePhrase(r))?m.cache(g,f):null,n=q.index+n.length-r.length,0<n&&(d=d.splitText(n)),n=d.length<=r.length?null:d.splitText(r.length),r&&!g&&(g={url:r.match(/^https?:\/\//i)?r:"http://"+r,type:"U"}),g&&(g.url.match(/https?:\/\//i)&&r&&w(g)&&u(f,d,g))&&(r=k(r,g),e.cache(r,"unlinked")||(h(r,d),T(r,g),d=
g.phrase||g.url,a[d]=a[d]||{count:0,phrase:g.phrase,type:g.type},a[d].count++)),d=n},k=function(a,b){var c;c=e.createEl("a");c.innerHTML=a.replace(/([a-z0-9]+ *|[^a-z0-9]+)/ig,"<span>$1</span>");c.className="vglnk";e.cache(c,"type","inserted");e.cache(c,"phrase",a);l.ui&&"U"!==b.type&&(c.title="Link added by VigLink");m.initLink(c,b);return c};return function(h,g){var k=m.regexp(g);a={};k&&(e.each(e.all(h,b),function(a){f(k,a,g)}),l.link_phrases&&m.log(a))}}(),insertManually:function(){var a=!1,b=
e.clone(l),f=function(a){return e.map(a,function(a,b){return{phrase:b,type:"M",url:a}})};return function(h,g,k){var p,q=!1;n.init();l.manual_mode&&!a&&(a=!0,p=g=g||{},l.same_proximity=p.same_proximity||l.same_proximity,l.proximity=p.proximity||l.proximity,l.per_page=p.per_page||l.per_page,l.per_phrase=p.per_phrase||l.per_phrase,p=g.target_node||document.body,h=f(h),m.loadPhrases(h,[p]),l=b,m.cache.reset(),q=!0,a=!1);"function"===e.type(k)&&k(q,p)}}(),loadPhrases:function(a,b,f){e.each(a,function(a){a.phrase&&
a.url&&(a.phrase=m.normalizePhrase(a.phrase),m.cache(a.phrase,{count:0,phrase:a.phrase,mid:a.mid,url:a.url,type:a.type||""},f))});m.hasCalled(f,!0);this.insertLinks(b,f)},log:function(b){var d=0,f=0,g=[];e.each(b,function(a,b){var c=parseInt(a.count,10);0<c&&("U"===a.type?f+=c:"M"!==a.type&&g.push({phrase:b,type:a.type,count:c}),d+=c)});0<d&&r("insert",[{ct:d,cl:f,exp:u,imp_id:a,phrases:e.toJSON(g)}])},normalizePhrase:function(a){return a.toLowerCase().replace(/(^\s+|\s+$)/g,"").split(/\s+/).join(" ")},
onInsertApi:function(c,d,f){b.opt("time_api")&&r.event.stop("ins");"object"===e.type(c)&&(u=c.exp,a=c.imp_id,c.results&&this.loadPhrases(c.results,d,f))},regexp:function(a){var b;a=m.cache(a);a=e.map(a,function(a,b){return e.escapeRegExp(b).split(" ").join("\\s+")});0<a.length&&(b="(?:^|[\\s\"'\\(])("+a.join("|")+")(?=\\s|\\W*$|\\W{2})",b=RegExp(q?"(?:"+b+"|"+q.source+")":b,"i"));return b||q}},n={init:e.destructing(e.bind(m.init,m)),initNodes:function(a){var b;l.scope&&(a=e.unique(e.reduce([],e.withScope(a,
l.scope),function(a,b){return a.concat(b[1])})));a.length&&(b=g.getPostIds(a),l.link_phrases&&!m.hasCalled(b)?m.getPhrases(a,b):m.insertLinks(a,b))}},l.manual_mode&&e.extend(n,{"public":{run:m.insertManually}}),n};window.vglnk=window.vglnk||{};window.vglnk.partners_plugin=function(l,e,b){var r={run:function(){var g,m=l.pai_type;e.isArray(m)&&m.length&&e.each(m,function(l){g=e.updateUrl(b.opt("api_url"),{pathname:"/api/sync.gif",search:"?"+e.toQuery({partner_id:l})});e.createEl("img").src=g})}};return{init:function(){r.run()}}};
